### ISSUE TITLE
Phar unable to run on servers

### ISSUE THREAD

**Issue by Jamiewarb** [hex-digital/acf-migrations#8]
The compiled phar, with the new repeater in repeater functionality, is unable to run on our servers. A Segmentation Fault is given. Likely to do with compilation of file

**Comment by Jamiewarb** [comment]
Instead of using .phar, we're now pulling the archived v1.0.0 tar, and running generate.php from inside that. This resulted in a successful migration.

**Comment by olivertappin** [comment]
This will need looking into, based on your server environment. I'll get in touch with you directly for that information. As for a workaround, you can run the following commands to run the `generate.php` file from the project directly:

```
curl -Lo acf-migrations-1.0.0.tar.gz https://github.com/hex-digital/acf-migrations/archive/v1.0.0.tar.gz
tar xvfz acf-migrations-*.tar.gz
php acf-migrations-*/generate.php -t /path/to/theme
rm -rf acf-migrations-*
```
